<?php

/** @var $block \Magento\Catalog\Block\Product\View\Addto\Compare */
?>

<?php $viewModel = $block->getData('addToCompareViewModel'); ?>
<?php if ($viewModel->isAvailableForCompare($block->getProduct())) :?>
<a href="#" data-post='<?= /* @noEscape */ $block->getPostDataParams() ?>'
        data-role="add-to-links"
        class="action tocompare">
        <img src="<?php echo $block->getViewFileUrl('images/compare.png') ?>" alt="compare" />
</a>
<?php endif; ?>

